version: '3.8'

services:
  rentx:
    container_name: rentx
    image: matheusgama/rentx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
    volumes:
      - ./src:/usr/src/app/src