version: '3.8'

services:
  db:
    image: postgres:15
    ports:
      - 5432:5432
    
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "mydb"
    
    volumes:
      - "./docker/db/pgdata:/var/lib/postgresql/data"