name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.16]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.16.0
      uses: actions/setup-node@v3
      with:
        node-version: 18.16.0
    - run: npm i
    - run: npm run build --if-present
